version: '3.7'
services:
  test-db:
    image: postgres:12.1-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=trivia_test